### ISSUE TITLE
v0.9.1 is not published on RubyGems.org

### ISSUE THREAD

**Issue by j15e** [microsoft/kiota-serialization-json-ruby#14]
Hello 👋 

When you have a moment, could you please release the latest version on [RubyGems](https://rubygems.org/gems/microsoft_kiota_serialization_json)?

Thanks!

**Comment by baywet** [comment]
Thanks for bringing this to our attention. I had messed up something in the tag (0.9.1 instead of v0.9.1) which didn't trigger the deployment workflow.
This is now fixed. Closing.
